### PR TITLE
Fix building for test

### PR DESCRIPTION
**Pull request by syguer**
Hi 😄 
I found some problems for testing.

1. Building puma is failed on `bundle  install` and looks it is caused by using too old version
2.  `uninitialized constant Rack::Auth` has raised because spec file requires only 'rake/builder'

I fixed these 👍

### CODE REVIEW

**Comment by syguer** [comment]
Hello?
No maintainer?

**Comment by syguer** [comment]
@tjarratt are you a maintainer?

**Comment by syguer** [comment]
@rubiii @timabdulla @tjarratt are you already not interested in this project?

**Comment by pcai** [comment]
Hi - thanks for the PR! I checked out master just now, and successfully built puma + ran tests fine. I prefer to not be locked to a beta version of puma, but I think puma 3.x drops support for ruby 2.0 though, I will revisit this when I have more clarity on the state of ruby 2.0 support in savon.

**Comment by pcai** [comment]
@syguer thanks for your contribution.

**Pull request merged**
