### PR TITLE
Test against ruby 2.3

### PR DESCRIPTION
**Pull request by antstorm**
Hi there,

Quick PR with 2 tiny changes — testing against new ruby version and using the latest `savon` version in the README.

### CODE REVIEW

**Comment by antstorm** [comment]
Oh wow, no ruby 2.3 in rvm? That's odd. Any objections against using `rbenv`? Seems to have a much better version support these days…

**Comment by antstorm** [comment]
#738 fixes non-related failing builds

**Comment by tjarratt** [comment]
Thank you for opening this pull request @antstorm! I greatly appreciate your time and the care you've shown here.

**Comment by antstorm** [comment]
@tjarratt happy to help!

**Pull request merged**
