### PR TITLE
MTOM support with tests

### PR DESCRIPTION
**Pull request by pcai**
**What kind of change is this?**

rebased https://github.com/savonrb/savon/pull/944 with tests

**Did you add tests for your changes?**

yes

**Summary of changes**

see https://github.com/savonrb/savon/pull/944

### CODE REVIEW

**Comment by chaadow** [comment]
hey @rubiii @pcai is it normal that this PR dissapeared entirely on `main` !! I can't find the changes at all

**Comment by rubiii** [comment]
Hey @chaadow it's still on the v3-legacy branch. Not sure if this got closed by accident. I can take a look at this later today when I'm out of meetings.

**Comment by rubiii** [comment]
Ok so there are actually a couple of changes in this.

* I fixed using attachments together with the `xml` option in d496e59.
* I would not pick the `nori` option, but I added the missing Nori options to Savon in c54f059 which hopefully fixes whatever the problem was.
* Regarding mtom itself, as far as I can see this does not fully implement mtom and doing that properly would take a week or two. But this or something like it might be enough to get people started and we could document it and also document the limitations. Not sure how many people still use this, but I can look into it.

**Comment by rubiii** [comment]
@chaadow Would you be able to give #1047 a try?

**Pull request merged**
