### PR TITLE
Don't Leak Wasabi::Resolver::HTTPError

### PR DESCRIPTION
**Pull request by sshaw**
RE: #654

### CODE REVIEW

**Comment by tjarratt** [comment]
Thank you so much for the pull request @sshaw ! I really appreciate it when people in the community pitch in to make Savon better.

**Comment by sshaw** [comment]
No thank you For producing a good SOAP library in Ruby! This lib has saved my team a lot of work and possibly some (more) JVM wrangling.

Death to SOAP for 98% of all use cases!

**Comment by patrice4github** [comment]
Sorry to be this late to the party. Was this merged? I'm still seeing this in 2.12.0:

`Wasabi::Resolver::HTTPError: Error: 301 for url http://ACORD.org/Standards/Life/2
./.rvm/gems/ruby-2.5.3@adn/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:45:in load_from_remote
./.rvm/gems/ruby-2.5.3@adn/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:33:in resolve
./.rvm/gems/ruby-2.5.3@adn/gems/wasabi-3.5.0/lib/wasabi/document.rb:142:in xml
/`

**Comment by sshaw** [comment]
@patrice4github this is indeed part of 2.12.0. Can you provide a bigger stacktrace, one that includes the Savon stack?

**Comment by patrice4github** [comment]
Sure.

It seems to happen when have the option: 

```
    client = Savon.client(
      wsdl: "http://ACORD.org/Standards/Life/2",
```

This is the correct wsdl the API owner wants, although it's an invalid WSDL URL (it redirect to a web page...)

Here it is:
```
Savon::HTTPError: HTTP error (301): <head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://www.ACORD.org/Standards/Life/2">here</a></body>
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/savon-2.12.0/lib/savon/operation.rb:27:in rescue in ensure_exists!
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/savon-2.12.0/lib/savon/operation.rb:21:in ensure_exists!
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/savon-2.12.0/lib/savon/operation.rb:15:in create
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/savon-2.12.0/lib/savon/client.rb:32:in operation
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/savon-2.12.0/lib/savon/client.rb:36:in call
/Users/patricegagnon/_projects/adn/adn-prod/lib/tasks/apexa.rake:81:in block (2 levels) in <top (required)>
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/rake-12.3.2/exe/rake:27:in <top (required)>
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/bin/ruby_executable_hooks:24:in eval
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/bin/ruby_executable_hooks:24:in <main>

Caused by:
Wasabi::Resolver::HTTPError: Error: 301 for url http://ACORD.org/Standards/Life/2
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:45:in load_from_remote
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:33:in resolve
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/wasabi-3.5.0/lib/wasabi/document.rb:142:in xml
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/wasabi-3.5.0/lib/wasabi/document.rb:160:in parse
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/wasabi-3.5.0/lib/wasabi/document.rb:147:in parser
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/wasabi-3.5.0/lib/wasabi/document.rb:64:in soap_actions
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/savon-2.12.0/lib/savon/operation.rb:22:in ensure_exists!
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/savon-2.12.0/lib/savon/operation.rb:15:in create
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/savon-2.12.0/lib/savon/client.rb:32:in operation
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/savon-2.12.0/lib/savon/client.rb:36:in call
/Users/patricegagnon/_projects/adn/adn-prod/lib/tasks/apexa.rake:81:in block (2 levels) in <top (required)>
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/gems/rake-12.3.2/exe/rake:27:in <top (required)>
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/bin/ruby_executable_hooks:24:in eval
/Users/patricegagnon/.rvm/gems/ruby-2.5.3@adn/bin/ruby_executable_hooks:24:in <main>
```

**Comment by sshaw** [comment]
Hi @patrice4github, 

Looking at the full stacktrace I can see that this PR is working as expected. 

It shows that `Savon::HTTPError` was indeed raised [from line 27 of `lib/savon/operation.rb`](https://github.com/savonrb/savon/pull/655/files#diff-603889093314d44060f58bbca9693a5eR27). 

In the next paragraph, is shows that `Wasabi::Resolver::HTTPError` was the original error: `Caused by: Wasabi::Resolver::HTTPError`. 


If you rescue `Savon::HTTPError` in your code you should be fine.

**Pull request merged**
