### PR TITLE
Add possibility to pass attribute delete_namespace_attributes to Nori

### PR DESCRIPTION
**Pull request by grzlus**
This change will solve #314 problem.

### CODE REVIEW

**Comment by rafaltrojanowski** [comment]
+ 1

**Comment by rafaltrojanowski** [comment]
+1

**Comment by rubysolo** [comment]
:+1:

**Comment by codebender** [comment]
:+1:

**Comment by astathopoulos** [comment]
We also need it. Could this be merged please?

**Comment by ehutzelman** [comment]
:+1:

**Pull request merged**
