### PR TITLE
Add Truffleruby head to CI

### PR DESCRIPTION
**Pull request by gogainda**
Add Truffleruby head to CI

### CODE REVIEW

**Comment by gogainda** [comment]
Tests are "passing", meaning that fail in the same way with other rubies

**Comment by gogainda** [comment]
@olleolleolle

**Comment by olleolleolle** [comment]
@gogainda Appreciate the ping, I filed this simple sign-post issue: https://github.com/savonrb/savon/issues/938

**Comment by olleolleolle** [comment]
@gogainda Hi! It seems we are now running on GitHub Actions CI.

That CI configuration does not currently include Ruby 3.0, it does hav `head`, though.

If you'd like to add TruffleRuby, JRuby, 3.0, another CI Pull Request would be appreciated. This one, ❤️ , we will say thanks to, and let go into the night. 👋

**Pull request closed without merging**
