### PR TITLE
Use proper namespaces for message content

### LINKED ISSUE #899: Namespace issue
The same issue has been reported at least 2 times, and was closed by that stupid bot.

Re-creating an issue because I can't open any of the previous ones.

#820 
#895 
#862

### PR DESCRIPTION
**Pull request by haider-cialfo**
Fixes #899 #820 #895 #862

### CODE REVIEW

**Comment by taschetto** [comment]
Can this be merged, please???

**Comment by lukaso** [comment]
Didn't notice this when I added my PR #917. That PR also has a breaking test. Would be very helpful for one of the two PRs to be merged.

**Comment by lukaso** [comment]
Given the slow pace of incorporating changes, I've created a gem that patches this issue. All you have to do is include it in your `Gemfile`:

```ruby
gem 'savon_fixes'
```

You can find the gem here: https://github.com/lukaso/savon_fixes. It currently covers off these issues and PRs: #916, #899, #820, #895, #862, #905 and #549 (they are all duplicates).

I haven't yet tested it in anger, but all tests pass, so please feedback if there are any issues. Adaptations of PRs here are also welcome.

**Comment by sergioisidoro** [comment]
@pcai We do have the same issue, and we have been hacking things along. 
Is there anything we can do to speed things up? Any help we can provide?

Should there be any other governance model, given that the gem seems to be on palliative care?

This gem has a significant amount of downloads so it's a major security issue to onboard new people or change ownership. But there has to be something the community can do to help?...

Also, please consider disabling the stale bot.

**Comment by olleolleolle** [comment]
👋 Thanks for all the work on fixing things, it really helps. ❤️ 

In order to merge this, even if it is a thing that looks like it's fixing outstanding issues, the test suite has not been amended with new cases.

So, to help this change get merged, add some kind of test (that would fail without this change) to the suite.

**Comment by lukaso** [comment]
This is a duplicate of #917 which has been merged (with test). This should be closed.

**Comment by pcai** [comment]
closing per prior comment

**Pull request closed without merging**
